# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c100543dd8fecc7595198f776b2810bb16d328b3d1e4fab96ca6f395ec8af830e246e0e3e6e01ef4dd2b80102c84c6d4fde2c004e9d840513e7b3bbfa4ad0c

test:
  secret_key_base: e7926ae6b5a64450bcd3229c542673c1a510462103881531da0620bfe3a548a667cddb6cdc206236a74a06a81f2cea9a517b7b22a5b16907fdb668ed71450e75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
